import Card from './Card';
import Badge from './Badge';

export default function PlaybookTimeline({ steps }) {
  return (
    <Card title="Autonomous Playbook (JSON View)" subtitle="Generated by TrustSphere reasoning engine">
      <div className="space-y-3 font-mono text-xs">
        {steps.map((step, idx) => (
          <div key={step.title} className="rounded-lg border border-white/10 bg-bg/50 p-3">
            <div className="mb-2 flex items-center justify-between gap-2">
              <span className="text-accent">"step_{idx + 1}": "{step.title}"</span>
              <Badge tone="violet">confidence: {step.confidence}%</Badge>
            </div>
            <p className="text-text/85">"action": "{step.detail}"</p>
            <p className="mt-1 text-text/65">"owner": "{step.owner}"</p>
          </div>
        ))}
      </div>
    </Card>
  );
}
